version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: render-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Nandini@2005
      MYSQL_DATABASE: vital_care_db
      MYSQL_USER: root
      MYSQL_PASSWORD: Nandini@2005
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
